apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: mariadb
spec:
  ports:
    - name: mariadb
      port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.targetPort }}
      protocol: TCP
  selector:
    app: mariadb