apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username | quote }}
  password: {{ .Values.credentials.password | quote }}
  rootpassword: {{ .Values.credentials.rootPassword | quote }}