apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-webapp
  namespace: {{ .Values.namespace.name }}
  labels:
    app: ecom-webapp
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: ecom-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ecom-webapp
    spec:
      containers:
        - name: ecom-webapp
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.path }}
              port: 80
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path }}
              port: 80
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.web.resources | nindent 12 }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appConfig.name }}
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appConfig.name }}
                  key: DB_NAME
            - name: FEATURE_DARK_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appConfig.name }}
                  key: FEATURE_DARK_MODE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: password
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: rootpassword